server:
  port: 8081

oauth2:
  clientId: "marketplace"
  secret: "secret"
  tokenValiditySeconds: 3600

spring:
  datasource:
    url: "jdbc:h2:/tmp/marketplace.db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE"
    driver-class-name: "org.h2.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
