server:
  port: 8081

oauth2:
  clientId: "marketplace"
  secret: "secret"
  tokenValiditySeconds: 3600

spring:
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://localhost:15432/aces_marketplace"
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: "validate"
      
  mail:
    host: "change-me"
    port: 587
    username: "change-me"
    password: "change-me"
    properties:
      mail.smtp.auth: true
      mail.startttls.enable: true

baseUrl: "http://localhost:4200"

recaptcha:
  secret: "change-me"

email:
  fromName: "ACES Marketplace"
  fromEmailAddress: "support@arkaces.com"
